# Generated by Django 5.1.6 on 2025-09-09 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('equipamento', '0001_initial'),
        ('piscina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('observacoes', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='cliente.cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='equipamento.equipamento')),
                ('piscina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='piscina.piscina')),
            ],
        ),
    ]
