# Generated by Django 5.1.6 on 2025-09-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='data_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
