# Generated by Django 5.1.6 on 2025-09-09 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamento', '0001_initial'),
        ('piscineiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='piscineiro.piscineiro'),
        ),
    ]
